name: test-check

on: push

jobs: 

  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: test check
        run: NODE_OPTIONS=--experimental-vm-modules npx jest 