name: test-check

on: push

jobs: 

  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: setting the environment
        run: NODE_OPTIONS=--experimental-vm-modules
      - name: test check
        run: npm test 